baseURL = "https://octetz.com"
languageCode = "en-us"
title = "octetz"

[params]

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/octetz/octetz'

  # Enable 'Edit this page' links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath = 'edit/master/octetz/content'

  # (Optional) Set this to true to enable 'Last Modified by' date and git author
  #  information on 'doc' type pages.
  enableGitInfo = true